{
 "title": "HTTP accesses",
 "description": "Approximate user locations (GeoIP)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "User locations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{geoip_continent_code=~\".+\"} | json | line_format `longitude={{.geoip_location_longitude}} latitude={{.geoip_location_latitude}}` | logfmt"
    }
   ]
  },
  {
   "title": "Unique IP per country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{service_name=\"planet_crs_registry\", geoip_continent_code=~\".+\"} | unpack"
    }
   ]
  },
  {
   "title": "Requests per country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{service_name=\"planet_crs_registry\", geoip_continent_code=~\".+\"} | unpack"
    }
   ]
  },
  { "title": "HTTP request statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP request count by path and method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{uri_path=~\".+\"}"
    }
   ]
  },
  {
   "title": "Request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "filters": [
      { "id": "0dc19937", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "planet_crs_registry" ],
       "valueType": "string"
      }
     ],
     "groupBy": [
      { "id": "8183311f", "scope": "span", "tag": "" }
     ],
     "limit": 20,
     "query": "{rootServiceName=\"python-webservice\"}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{level=~\"ERROR|WARN\"} |= `` | unpack | line_format `{{ regexReplaceAll \"exception\\\\.\" __line__ \"\" }}` | json reason=\"attributes.message\", stacktrace=\"attributes.stacktrace\", body=\"body\" | label_format message=`{{ default .body .reason }}`"
    }
   ]
  },
  {
   "title": "HTTP return codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{status_code=~\"\\\\d+\"} |= ``"
    }
   ]
  }
 ]
}